const TimeIntervalMethod = {
    AROUND_TIME_INSTANT: "TIME_INTERVAL.AROUND_TIME_INSTANT",
    IN_DAILY_INTERVAL: "TIME_INTERVAL.IN_DAILY_INTERVAL",
    IN_INTERVAL: "TIME_INTERVAL.IN_INTERVAL",
    IN_INTERVAL_OF_DAY: "TIME_INTERVAL.IN_INTERVAL_OF_DAY",
    IN_TIME_INTERVAL: "TIME_INTERVAL.IN_TIME_INTERVAL",
    MORNING:"TIME_INTERVAL.MORNING" , 
    AFTERNOON:"TIME_INTERVAL.AFTERNOON",
    EVENING:"TIME_INTERVAL.EVENING",
    NIGHT:"TIME_INTERVAL.NIGHT",
    WEEKDAY:"TIME_INTERVAL.WEEKDAY",
    WEEKEND:"TIME_INTERVAL.WEEKEND",
    HOLIDAY:"TIME_INTERVAL.HOLIDAY"
}

export default TimeIntervalMethod;