const TimeIntervalMethod = {
    AROUND_TIME_INSTANT: "TIME_INTERVAL.AROUND_TIME_INSTANT",
    IN_DAILY_INTERVAL: "TIME_INTERVAL.IN_DAILY_INTERVAL",
    IN_INTERVAL: "TIME_INTERVAL.IN_INTERVAL",
    IN_INTERVAL_OF_DAY: "TIME_INTERVAL.IN_INTERVAL_OF_DAY",
    IN_TIME_INTERVAL: "TIME_INTERVAL.IN_TIME_INTERVAL",
}

export default TimeIntervalMethod;